# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Post',
        ),
    ]
