# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expence',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
