# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_management', '0002_expence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
