# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_management', '0003_auto_20170213_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expence',
            new_name='Expense',
        ),
    ]
